# Generated by Django 6.0.4 on 2026-04-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(verbose_name='使用者輸入')),
                ('bot_response', models.TextField(verbose_name='仿生人回覆')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '對話紀錄',
                'verbose_name_plural': '對話紀錄',
            },
        ),
    ]
