# Generated by Django 6.0.1 on 2026-03-10 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('description', models.TextField(blank=True, verbose_name='分類描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '教材分類',
                'verbose_name_plural': '教材分類',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='教材標題')),
                ('file', models.FileField(upload_to='study_materials/%Y/%m/', verbose_name='教材檔案')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='study_brain.category', verbose_name='所屬分類')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '教材檔案',
                'verbose_name_plural': '教材檔案',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='重點整理')),
                ('questions_data', models.JSONField(default=list, verbose_name='練習題資料')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='產出時間')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='study_brain.material', verbose_name='關聯教材')),
            ],
            options={
                'verbose_name': 'AI 分析結果',
                'verbose_name_plural': 'AI 分析結果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(verbose_name='總題數')),
                ('correct_count', models.IntegerField(verbose_name='答對題數')),
                ('error_rate', models.FloatField(verbose_name='錯誤率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='測驗時間')),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_brain.analysisresult', verbose_name='測驗來源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_records', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '測驗紀錄',
                'verbose_name_plural': '測驗紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='題目內容')),
                ('user_answer', models.TextField(verbose_name='使用者答案')),
                ('correct_answer', models.TextField(verbose_name='正確答案')),
                ('quiz_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='study_brain.quizrecord', verbose_name='所屬測驗紀錄')),
            ],
            options={
                'verbose_name': '錯題明細',
                'verbose_name_plural': '錯題明細',
            },
        ),
        migrations.CreateModel(
            name='ReadingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='閱讀時間')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_brain.material', verbose_name='閱讀教材')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '閱讀紀錄',
                'verbose_name_plural': '閱讀紀錄',
                'ordering': ['-read_at'],
            },
        ),
    ]
