# Generated by Django 6.0.1 on 2026-03-10 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_brain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_materials', to=settings.AUTH_USER_MODEL, verbose_name='收藏的使用者'),
        ),
    ]
