# Generated by Django 6.0.1 on 2026-03-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_brain', '0002_material_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmistake',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='解析說明'),
        ),
    ]
