# Generated by Django 6.0.1 on 2026-03-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_brain', '0003_quizmistake_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_exam_paper',
            field=models.BooleanField(default=False, verbose_name='是否為歷屆考題'),
        ),
    ]
