# Generated by Django 6.0.1 on 2026-03-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_brain', '0004_material_is_exam_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecord',
            name='attempted_questions',
            field=models.JSONField(blank=True, default=list, verbose_name='已作答題目'),
        ),
    ]
