# Generated by Django 6.0.1 on 2026-03-16 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_brain', '0005_quizrecord_attempted_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDeepAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField(verbose_name='題目索引(原題號)')),
                ('concept_explanation', models.TextField(verbose_name='觀念深度解析(Markdown)')),
                ('practice_questions', models.JSONField(default=list, verbose_name='3題相關練習題')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成時間')),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_analyses', to='study_brain.analysisresult', verbose_name='對應測驗卷')),
            ],
            options={
                'verbose_name': 'AI 深度解析',
                'verbose_name_plural': 'AI 深度解析',
                'unique_together': {('analysis_result', 'question_index')},
            },
        ),
    ]
