# Generated by Django 6.0.3 on 2026-04-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TubeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='來源網址')),
                ('title', models.CharField(max_length=255, verbose_name='資源標題')),
                ('category', models.CharField(choices=[('course', '課堂學習'), ('ktv', '練唱歌')], default='course', max_length=10, verbose_name='資源分類')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='tube_hub/videos/', verbose_name='影片檔')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tube_hub/audios/', verbose_name='音檔')),
                ('primary_content', models.TextField(blank=True, null=True, verbose_name='主內容 (原生字幕/歌詞)')),
                ('secondary_content', models.TextField(blank=True, null=True, verbose_name='副內容 (AI 處理結果)')),
                ('personal_notes', models.TextField(blank=True, null=True, verbose_name='個人學習筆記')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '影音資源',
                'verbose_name_plural': '影音資源',
            },
        ),
    ]
