# Generated by Django 6.0.3 on 2026-04-07 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tuberesource',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開分享給他人'),
        ),
        migrations.AddField(
            model_name='tuberesource',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='擁有者'),
        ),
        migrations.AlterField(
            model_name='tuberesource',
            name='url',
            field=models.URLField(verbose_name='來源網址'),
        ),
        migrations.CreateModel(
            name='TubeFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='資料夾名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '收藏資料夾',
                'verbose_name_plural': '收藏資料夾',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='tuberesource',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tube_hub.tubefolder', verbose_name='所屬資料夾'),
        ),
    ]
