# Generated by Django 6.0.3 on 2026-04-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube_hub', '0002_tuberesource_is_public_tuberesource_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuberesource',
            name='category',
            field=models.CharField(choices=[('course', '影片'), ('ktv', '音樂')], default='course', max_length=10, verbose_name='資源分類'),
        ),
        migrations.AlterField(
            model_name='tuberesource',
            name='personal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='個人筆記'),
        ),
    ]
