# Generated by Django 6.0.4 on 2026-04-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube_hub', '0003_alter_tuberesource_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubefolder',
            name='folder_type',
            field=models.CharField(choices=[('course', '影片資料夾'), ('ktv', '音樂歌單')], default='course', max_length=10, verbose_name='類型'),
        ),
        migrations.AlterField(
            model_name='tuberesource',
            name='primary_content',
            field=models.TextField(blank=True, null=True, verbose_name='主內容'),
        ),
        migrations.AlterField(
            model_name='tuberesource',
            name='secondary_content',
            field=models.TextField(blank=True, null=True, verbose_name='副內容'),
        ),
    ]
