# Generated by Django 6.0.5 on 2026-07-07 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0004_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未命名寵物', max_length=50, verbose_name='寵物名字')),
                ('pet_type', models.CharField(choices=[('DRAGON', '幻獸綠龍'), ('PUPPY', '烈火幼犬')], default='DRAGON', max_length=20, verbose_name='寵物種類')),
                ('stage', models.IntegerField(choices=[(0, '寵物蛋'), (1, '幼年體'), (2, '成長體'), (3, '完全體'), (4, '進化體')], default=0, verbose_name='成長階段')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否出戰')),
                ('growth_progress', models.PositiveIntegerField(default=0, verbose_name='成長進度')),
                ('login_days_consumed', models.PositiveIntegerField(default=0, verbose_name='已消耗登入天數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='領養時間')),
                ('last_interacted_at', models.DateTimeField(auto_now=True, verbose_name='最後互動時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '寵物',
                'verbose_name_plural': '寵物',
            },
        ),
        migrations.CreateModel(
            name='DailyLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(verbose_name='登入日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '每日登入日誌',
                'verbose_name_plural': '每日登入日誌',
                'unique_together': {('user', 'login_date')},
            },
        ),
        migrations.CreateModel(
            name='PetStoryUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('DRAGON', '幻獸綠龍'), ('PUPPY', '烈火幼犬')], max_length=20, verbose_name='寵物種類')),
                ('max_stage_reached', models.IntegerField(default=0, verbose_name='已解鎖最高成長階段')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '劇情解鎖紀錄',
                'verbose_name_plural': '劇情解鎖紀錄',
                'unique_together': {('user', 'pet_type')},
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='擁有數量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.product', verbose_name='道具商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者背包道具',
                'verbose_name_plural': '使用者背包道具',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
