# Generated by Django 6.0.5 on 2026-07-07 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='equipped_back',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='背部裝飾'),
        ),
        migrations.AddField(
            model_name='pet',
            name='equipped_face',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='臉部裝飾'),
        ),
        migrations.AddField(
            model_name='pet',
            name='equipped_head',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='頭部裝飾'),
        ),
        migrations.AddField(
            model_name='pet',
            name='feed_items_consumed',
            field=models.PositiveIntegerField(default=0, verbose_name='普通乾糧消耗數'),
        ),
        migrations.AddField(
            model_name='pet',
            name='personality',
            field=models.CharField(choices=[('NORMAL', '普通'), ('BRAVE', '勇敢'), ('LAZY', '懶散'), ('SMART', '聰明'), ('CHUBBY', '肥嘟嘟')], default='NORMAL', max_length=20, verbose_name='寵物性格'),
        ),
        migrations.AddField(
            model_name='pet',
            name='potions_consumed',
            field=models.PositiveIntegerField(default=0, verbose_name='奇蹟藥水消耗數'),
        ),
        migrations.CreateModel(
            name='PetExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_hours', models.IntegerField(verbose_name='探索時長(小時)')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='出發時間')),
                ('end_time', models.DateTimeField(verbose_name='預計結束時間')),
                ('status', models.CharField(choices=[('ACTIVE', '探索中'), ('COMPLETED', '探索完成'), ('CLAIMED', '已領取獎勵')], default='ACTIVE', max_length=20, verbose_name='狀態')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='pet_system.pet', verbose_name='派遣寵物')),
            ],
            options={
                'verbose_name': '探索派遣任務',
                'verbose_name_plural': '探索派遣任務',
            },
        ),
        migrations.CreateModel(
            name='TowerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.PositiveIntegerField(default=1, verbose_name='當前爬塔層數')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tower_progress', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '爬塔進度',
                'verbose_name_plural': '爬塔進度',
            },
        ),
        migrations.CreateModel(
            name='UserPetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_gold_coins', models.PositiveIntegerField(default=0, verbose_name='寵物金幣')),
                ('last_daily_claim', models.DateField(blank=True, null=True, verbose_name='最後每日金幣領取日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '玩家寵物存摺',
                'verbose_name_plural': '玩家寵物存摺',
            },
        ),
        migrations.CreateModel(
            name='UserAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_id', models.CharField(max_length=50, verbose_name='配件ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='擁有數量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '玩家解鎖配件',
                'verbose_name_plural': '玩家解鎖配件',
                'unique_together': {('user', 'accessory_id')},
            },
        ),
    ]
