# Generated by Django 6.0.7 on 2026-07-15 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_system', '0002_pet_equipped_back_pet_equipped_face_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未命名寵物', max_length=50, verbose_name='寵物名字')),
                ('pet_type', models.CharField(choices=[('DRAGON', '幻獸綠龍'), ('PUPPY', '烈火幼犬')], default='DRAGON', max_length=20, verbose_name='寵物種類')),
                ('stage', models.IntegerField(choices=[(0, '寵物蛋'), (1, '幼年體'), (2, '成長體'), (3, '完全體'), (4, '進化體')], default=0, verbose_name='成長階段')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否出戰')),
                ('growth_progress', models.PositiveIntegerField(default=0, verbose_name='成長進度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='領養時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_pets', to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
            options={
                'verbose_name': 'LINE 寵物',
                'verbose_name_plural': 'LINE 寵物',
            },
        ),
        migrations.CreateModel(
            name='LinePetInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eggs_dragon', models.PositiveIntegerField(default=0, verbose_name='綠龍蛋數量')),
                ('eggs_puppy', models.PositiveIntegerField(default=0, verbose_name='火犬蛋數量')),
                ('evo_potions', models.PositiveIntegerField(default=0, verbose_name='進化藥水數量')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_pet_inventory', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'LINE 寵物背包',
                'verbose_name_plural': 'LINE 寵物背包',
            },
        ),
        migrations.CreateModel(
            name='LinePetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_gold_coins', models.PositiveIntegerField(default=100, verbose_name='LINE 寵物金幣')),
                ('last_sync_date', models.DateField(blank=True, null=True, verbose_name='最後步數同步日期')),
                ('last_sync_steps', models.PositiveIntegerField(default=0, verbose_name='最後同步步數')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_pet_profile', to=settings.AUTH_USER_MODEL, verbose_name='LINE 使用者')),
            ],
            options={
                'verbose_name': 'LINE 玩家寵物存摺',
                'verbose_name_plural': 'LINE 玩家寵物存摺',
            },
        ),
    ]
