# Generated by Django 6.0.7 on 2026-07-16 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_system', '0003_linepet_linepetinventory_linepetprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFitToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Google Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Google Refresh Token')),
                ('expires_at', models.FloatField(verbose_name='過期時間戳')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_fit_token', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'Google Fit 憑證',
                'verbose_name_plural': 'Google Fit 憑證',
            },
        ),
    ]
