# Generated by Django 6.0.7 on 2026-07-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_system', '0004_googlefittoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlefittoken',
            name='google_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google 帳號 Email'),
        ),
    ]
