# Generated by Django 6.0.7 on 2026-07-16 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_system', '0005_googlefittoken_google_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='linepet',
            name='equipped_back',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='背部裝飾'),
        ),
        migrations.AddField(
            model_name='linepet',
            name='equipped_face',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='臉部裝飾'),
        ),
        migrations.AddField(
            model_name='linepet',
            name='equipped_head',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='頭部裝飾'),
        ),
        migrations.AddField(
            model_name='linepet',
            name='feed_items_consumed',
            field=models.PositiveIntegerField(default=0, verbose_name='普通乾糧消耗數'),
        ),
        migrations.AddField(
            model_name='linepet',
            name='personality',
            field=models.CharField(choices=[('NORMAL', '普通'), ('BRAVE', '勇敢'), ('LAZY', '懶散'), ('SMART', '聰明'), ('CHUBBY', '肥嘟嘟')], default='NORMAL', max_length=20, verbose_name='寵物性格'),
        ),
        migrations.AddField(
            model_name='linepet',
            name='potions_consumed',
            field=models.PositiveIntegerField(default=0, verbose_name='奇蹟藥水消耗數'),
        ),
        migrations.AddField(
            model_name='linepetprofile',
            name='last_daily_claim',
            field=models.DateField(blank=True, null=True, verbose_name='最後每日金幣領取日期'),
        ),
        migrations.CreateModel(
            name='LinePetExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_hours', models.IntegerField(verbose_name='探索時長(小時)')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='出發時間')),
                ('end_time', models.DateTimeField(verbose_name='預計結束時間')),
                ('status', models.CharField(choices=[('ACTIVE', '探索中'), ('COMPLETED', '探索完成'), ('CLAIMED', '已領取獎勵')], default='ACTIVE', max_length=20, verbose_name='狀態')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='pet_system.linepet', verbose_name='派遣寵物')),
            ],
            options={
                'verbose_name': 'LINE 寵物探索派遣任務',
                'verbose_name_plural': 'LINE 寵物探索派遣任務',
            },
        ),
    ]
