# Generated by Django 6.0.7 on 2026-07-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_system', '0006_linepet_equipped_back_linepet_equipped_face_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linepet',
            options={'verbose_name': '休閒小站角色', 'verbose_name_plural': '休閒小站角色'},
        ),
        migrations.RemoveField(
            model_name='linepet',
            name='equipped_back',
        ),
        migrations.RemoveField(
            model_name='linepet',
            name='equipped_face',
        ),
        migrations.RemoveField(
            model_name='linepet',
            name='equipped_head',
        ),
        migrations.AddField(
            model_name='linepet',
            name='exp',
            field=models.PositiveIntegerField(default=0, verbose_name='角色經驗值'),
        ),
        migrations.AddField(
            model_name='linepet',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='角色等級'),
        ),
        migrations.AlterField(
            model_name='linepet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='解鎖時間'),
        ),
        migrations.AlterField(
            model_name='linepet',
            name='name',
            field=models.CharField(default='芙莉蓮', max_length=50, verbose_name='角色名字'),
        ),
        migrations.AlterField(
            model_name='linepet',
            name='personality',
            field=models.CharField(choices=[('NORMAL', '普通'), ('BRAVE', '勇敢'), ('LAZY', '懶散'), ('SMART', '聰明'), ('CHUBBY', '肥嘟嘟')], default='NORMAL', max_length=20, verbose_name='角色性格'),
        ),
        migrations.AlterField(
            model_name='linepet',
            name='pet_type',
            field=models.CharField(choices=[('FRIEREN', '芙莉蓮'), ('RIMURU', '利姆路'), ('DRAGON', '綠光小龍'), ('PUPPY', '烈火幼犬')], default='FRIEREN', max_length=20, verbose_name='角色種類'),
        ),
        migrations.AlterField(
            model_name='linepet',
            name='stage',
            field=models.IntegerField(choices=[(0, '未解鎖'), (1, '冒險者'), (2, '精英'), (3, '大師'), (4, '傳奇')], default=1, verbose_name='階級'),
        ),
    ]
