# Generated by Django 6.0.7 on 2026-08-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_system', '0007_alter_linepet_options_remove_linepet_equipped_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linepet',
            name='feed_items_consumed',
        ),
        migrations.RemoveField(
            model_name='linepet',
            name='growth_progress',
        ),
        migrations.RemoveField(
            model_name='linepet',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='linepet',
            name='potions_consumed',
        ),
        migrations.RemoveField(
            model_name='linepet',
            name='stage',
        ),
        migrations.AddField(
            model_name='linepet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
        ),
        migrations.AlterField(
            model_name='linepet',
            name='pet_type',
            field=models.CharField(choices=[('FRIEREN', '芙莉蓮'), ('RIMURU', '利姆路')], default='FRIEREN', max_length=20, verbose_name='角色種類'),
        ),
    ]
