# Generated by Django 6.0.7 on 2026-08-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_system', '0008_remove_linepet_feed_items_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linepet',
            name='name',
            field=models.CharField(default='芙莉蓮', max_length=50, verbose_name='角色名稱'),
        ),
        migrations.AlterField(
            model_name='linepet',
            name='pet_type',
            field=models.CharField(default='芙莉蓮', max_length=50, verbose_name='角色種類/識別標籤'),
        ),
    ]
