# Generated by Django 6.0.7 on 2026-08-07 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_system', '0009_alter_linepet_name_alter_linepet_pet_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinePetGiftClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_id', models.CharField(max_length=100, verbose_name='禮物識別碼')),
                ('coins', models.PositiveIntegerField(default=0, verbose_name='領取金額')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='領取時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_claims', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '禮物領取紀錄',
                'verbose_name_plural': '禮物領取紀錄',
                'unique_together': {('user', 'gift_id')},
            },
        ),
    ]
