services:
  db:
    image: mysql:8.0
    container_name: csi_mysql
    restart: always
    environment:
      MYSQL_DATABASE: csi_db
      MYSQL_ROOT_PASSWORD: 78951235
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: csi_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4041:4040"
    tty: true
    stdin_open: true
    entrypoint: [
      "ngrok", "http", "web:8000",
      "--domain=unjoinable-scribal-vanesa.ngrok-free.dev",
      "--log=stdout"
    ]
    depends_on:
      - web

volumes:
  mysql_data: