task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ["bbox"]

num_classes: 2

train_dataloader:
  type: DataLoader
  dataset:
    type: HandProtectionDetection
    select_file: ./dataset/hand_protection/split_info/training.txt
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 16
  drop_last: True
  collate_fn:
    type: BatchImageCollateFuncion

val_dataloader:
  type: DataLoader
  dataset:
    type: HandProtectionDetection
    select_file: ./dataset/hand_protection/split_info/validation.txt
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 16
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
