# Generated by Django 6.0.1 on 2026-01-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('lucky_draw', '幸運大轉盤'), ('ticket_pull', '發文簿系統'), ('profile_edit', '個人化大頭貼'), ('ai_chat', 'AI 智能客服'), ('announcement', '公告系統'), ('admin_panel', '管理後台')], max_length=50, unique=True, verbose_name='功能名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='全局啟用狀態')),
                ('guest_access', models.BooleanField(default=False, verbose_name='訪客可用')),
                ('user_access', models.BooleanField(default=False, verbose_name='一般用戶可用')),
                ('staff_access', models.BooleanField(default=False, verbose_name='工作人員可用')),
                ('superuser_access', models.BooleanField(default=True, verbose_name='管理員可用')),
                ('description', models.TextField(blank=True, verbose_name='功能簡介')),
            ],
            options={
                'verbose_name': '功能權限管理',
                'verbose_name_plural': '功能權限管理',
            },
        ),
    ]
