# Generated by Django 6.0.1 on 2026-01-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurestatus',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '功能權限管理', 'verbose_name_plural': '功能權限管理'},
        ),
        migrations.AddField(
            model_name='featurestatus',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='顯示順序'),
        ),
    ]
