# Generated by Django 6.0.1 on 2026-02-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_featurestatus_options_featurestatus_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurestatus',
            name='name',
            field=models.CharField(choices=[('lucky_draw', '幸運大轉盤'), ('ticket_pull', '發文簿系統'), ('profile_edit', '個人化大頭貼'), ('ai_chat', 'AI 智能客服'), ('announcement', '公告系統'), ('admin_panel', '管理後台'), ('tigf', '安定系統')], max_length=50, unique=True, verbose_name='功能名稱'),
        ),
    ]
