# Generated by Django 6.0.4 on 2026-04-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enterpriseinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterpriseinfo',
            options={'verbose_name': '企業資訊', 'verbose_name_plural': '企業資訊管理'},
        ),
    ]
