# Generated by Django 6.0.1 on 2026-03-04 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='方案名稱')),
                ('price', models.PositiveIntegerField(verbose_name='台幣售價')),
                ('deposit_points', models.PositiveIntegerField(verbose_name='獲得儲值點數')),
                ('bonus_points', models.PositiveIntegerField(default=0, verbose_name='加贈紅利點數')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '儲值方案',
                'verbose_name_plural': '儲值方案',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('price_in_points', models.PositiveIntegerField(verbose_name='點數售價')),
                ('price_ntd', models.PositiveIntegerField(default=0, verbose_name='台幣售價')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存數量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '商城商品',
                'verbose_name_plural': '商城商品',
            },
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_trade_no', models.CharField(max_length=50, unique=True)),
                ('amount', models.PositiveIntegerField(verbose_name='儲值金額')),
                ('status', models.CharField(choices=[('PENDING', '待付款'), ('SUCCESS', '付款成功'), ('FAILED', '付款失敗')], default='PENDING', max_length=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECHARGE', '儲值'), ('PURCHASE', '購物扣抵'), ('REWARD', '活動贈送'), ('REFUND', '退貨返還')], max_length=20, verbose_name='交易類型')),
                ('point_type', models.CharField(choices=[('DEPOSIT', '儲值點數'), ('BONUS', '紅利點數')], max_length=10, verbose_name='點數類型')),
                ('amount', models.IntegerField(verbose_name='變動金額')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='關聯單號')),
                ('description', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to=settings.AUTH_USER_MODEL)),
                ('recharge_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.rechargeorder')),
            ],
            options={
                'verbose_name': '點數交易紀錄',
                'verbose_name_plural': '點數交易紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='購買數量')),
                ('payment_method', models.CharField(choices=[('POINTS', '點數全額扣抵'), ('ECPAY', '綠界金流付款')], default='POINTS', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '待付款'), ('PAID', '已付款'), ('FAILED', '付款失敗')], default='COMPLETED', max_length=20)),
                ('total_price', models.PositiveIntegerField(verbose_name='總點數花費')),
                ('deposit_used', models.PositiveIntegerField(default=0, verbose_name='使用儲值點數')),
                ('bonus_used', models.PositiveIntegerField(default=0, verbose_name='使用紅利點數')),
                ('amount_paid', models.PositiveIntegerField(default=0, verbose_name='台幣實付金額')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '點數購物訂單',
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_points', models.PositiveIntegerField(default=0, verbose_name='儲值點數')),
                ('bonus_points', models.PositiveIntegerField(default=0, verbose_name='紅利點數')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '錢包餘額',
                'verbose_name_plural': '錢包餘額',
            },
        ),
    ]
