# Generated by Django 6.0.1 on 2026-03-10 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rechargeorder',
            options={'verbose_name': '綠界儲值訂單', 'verbose_name_plural': '綠界儲值訂單'},
        ),
        migrations.AlterModelOptions(
            name='shoporder',
            options={'verbose_name': '點數購物訂單', 'verbose_name_plural': '點數購物訂單'},
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='recharge_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.rechargeorder', verbose_name='關聯儲值訂單'),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='rechargeorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='rechargeorder',
            name='merchant_trade_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='特店交易編號'),
        ),
        migrations.AlterField(
            model_name='rechargeorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款時間'),
        ),
        migrations.AlterField(
            model_name='rechargeorder',
            name='status',
            field=models.CharField(choices=[('PENDING', '待付款'), ('SUCCESS', '付款成功'), ('FAILED', '付款失敗')], default='PENDING', max_length=10, verbose_name='訂單狀態'),
        ),
        migrations.AlterField(
            model_name='rechargeorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='payment_method',
            field=models.CharField(choices=[('POINTS', '點數全額扣抵'), ('ECPAY', '綠界金流付款')], default='POINTS', max_length=10, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.product', verbose_name='購買商品'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('PENDING', '待付款'), ('PAID', '已付款'), ('FAILED', '付款失敗')], default='COMPLETED', max_length=20, verbose_name='訂單狀態'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
    ]
