# Generated by Django 6.0.5 on 2026-07-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_rechargeorder_options_alter_shoporder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GENERAL', '一般商品'), ('PET_EGG', '寵物蛋'), ('PET_FOOD', '寵物成長道具')], default='GENERAL', max_length=20, verbose_name='商品分類'),
        ),
    ]
