# Generated by Django 6.0.1 on 2026-03-05 06:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='代碼')),
                ('name', models.CharField(max_length=100, verbose_name='標的名稱')),
                ('exchange', models.CharField(default='TWSE', max_length=20, verbose_name='交易所')),
                ('category', models.CharField(choices=[('STOCK', '股票'), ('ETF', '指數型基金')], default='STOCK', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='組合名稱')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='當前股價')),
                ('daily_change', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='今日漲跌')),
                ('daily_change_percent', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='漲跌幅(%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='invest.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', '買入'), ('SELL', '賣出'), ('DIVIDEND', '股息')], max_length=10)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='成交股數')),
                ('price_per_share', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='成交單價')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='手續費')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='稅金')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invest.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.stock')),
            ],
            options={
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shares', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='總持股數')),
                ('average_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='平均成本')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='invest.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.stock')),
            ],
            options={
                'unique_together': {('portfolio', 'stock')},
            },
        ),
    ]
