# Generated by Django 6.0.1 on 2026-03-05 08:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'verbose_name': '當前持股', 'verbose_name_plural': '當前持股'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': '投資組合', 'verbose_name_plural': '投資組合'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '標的資訊', 'verbose_name_plural': '標的資訊'},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'verbose_name': '行情快取', 'verbose_name_plural': '行情快取'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-trade_date', '-created_at'], 'verbose_name': '交易紀錄', 'verbose_name_plural': '交易紀錄'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='expected_dividend_yield',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='預估殖利率(%)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='target_monthly_income',
            field=models.DecimalField(decimal_places=0, default=Decimal('30000'), max_digits=10, verbose_name='每月被動收入目標'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='invest.portfolio', verbose_name='投資組合'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.stock', verbose_name='標的'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='所屬用戶'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('STOCK', '股票'), ('ETF', '指數型基金')], default='STOCK', max_length=10, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用狀態'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='invest.stock', verbose_name='標的'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invest.portfolio', verbose_name='投資組合'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invest.stock', verbose_name='標的'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', '買入'), ('SELL', '賣出'), ('DIVIDEND', '股息')], max_length=10, verbose_name='交易類型'),
        ),
    ]
