# Generated by Django 6.0.1 on 2026-03-06 01:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_alter_holding_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='已實現損益'),
        ),
    ]
