# Generated by Django 6.0.1 on 2026-01-27 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置頂')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='發布者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告管理',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
