# Generated by Django 6.0.1 on 2026-01-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='工具名稱')),
                ('url', models.URLField(verbose_name='網址')),
                ('icon_class', models.CharField(default='fas fa-external-link-alt', max_length=50, verbose_name='FontAwesome 圖示碼')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '外部工具',
                'verbose_name_plural': '外部工具管理',
                'ordering': ['order'],
            },
        ),
    ]
