# Generated by Django 6.0.1 on 2026-01-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_externaltool'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_text', models.TextField(verbose_name='系統基本指令')),
                ('website_info', models.TextField(blank=True, verbose_name='網站功能資訊')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI 客服設定',
                'verbose_name_plural': 'AI 客服設定',
            },
        ),
    ]
