# Generated by Django 6.0.1 on 2026-01-29 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_aisystemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='總瀏覽量')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='統計日期')),
                ('daily_count', models.PositiveIntegerField(default=0, verbose_name='當日瀏覽量')),
            ],
            options={
                'verbose_name': '網站瀏覽統計',
                'verbose_name_plural': '網站瀏覽統計',
            },
        ),
    ]
