# Generated by Django 6.0.1 on 2026-01-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0004_sitevisit"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(auto_now_add=True, verbose_name="日期")),
                ("serial_number", models.CharField(max_length=11, unique=True, verbose_name="發文字號")),
                ("matter", models.CharField(max_length=20, verbose_name="事由")),
                ("applicant", models.CharField(max_length=10, verbose_name="取號人")),
            ],
            options={
                "verbose_name": "發文簿紀錄",
                "ordering": ["-date"],
            },
        ),
    ]
