# Generated by Django 6.0.1 on 2026-01-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_ticketrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisystemsetting',
            name='role_level',
            field=models.CharField(choices=[('GUEST', '未登入訪客'), ('USER', '一般使用者'), ('STAFF', '工作人員'), ('SUPERUSER', '超級管理員')], default='GUEST', max_length=20, verbose_name='適用權限'),
        ),
        migrations.AlterField(
            model_name='aisystemsetting',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否啟用'),
        ),
    ]
