# Generated by Django 6.0.1 on 2026-02-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_aisystemsetting_role_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisystemsetting',
            name='internal_policy',
            field=models.TextField(blank=True, verbose_name='內部政策'),
        ),
        migrations.AlterField(
            model_name='aisystemsetting',
            name='role_level',
            field=models.CharField(choices=[('GUEST', '未登入訪客'), ('USER', '一般使用者'), ('STAFF', '工作人員'), ('SUPERUSER', '超級管理員'), ('EMPLOYEE', '專屬公司職員')], default='GUEST', max_length=20, verbose_name='適用權限'),
        ),
    ]
