# Generated by Django 6.0.1 on 2026-03-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_aisystemsetting_internal_policy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketrecord',
            options={'ordering': ['-date'], 'verbose_name': '發文簿紀錄', 'verbose_name_plural': '發文簿紀錄'},
        ),
        migrations.AlterField(
            model_name='aisystemsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
