# Generated by Django 6.0.4 on 2026-04-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_alter_ticketrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltool',
            name='url',
            field=models.CharField(max_length=255, verbose_name='網址'),
        ),
    ]
