"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ  # * 匯入 django-environ
import os

from pathlib import Path


#! 初始化 environ，設定變數型別與預設值
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
)

BASE_DIR = Path(__file__).resolve().parent.parent

#! 讀取 .env 檔案
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

#! 從 env 中提取機敏資料
SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")
ALLOWED_HOSTS = env("ALLOWED_HOSTS")
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # * allauth 必備
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",  # * 啟用 Google 登入
    "crispy_forms",
    "crispy_bootstrap5",  # * Bootstrap 5 樣式支援
    "core",
]

#! 開發環境才執行
if DEBUG:
    INSTALLED_APPS += [
        "django_extensions",  # * 這樣在本機才能執行 shell_plus
    ]
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # * 將信件內容印在終端機而非真的寄出

#! allauth 需要 SITE_ID
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # * Django 預設
    "allauth.account.auth_backends.AuthenticationBackend",  # * allauth 專用
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

#! 指定登入與識別方式 (只使用 Email)
ACCOUNT_LOGIN_METHODS = {"email"}

#! 定義註冊表單欄位 (星號代表必填)
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

#! 驗證信設定
ACCOUNT_EMAIL_VERIFICATION = "optional"
"""
"mandatory": 強制驗證。使用者必須點擊驗證信連結才能登入（Local 測試較麻煩）。
"optional": 選用驗證。會發送驗證信，但使用者不驗證也能直接登入（適合目前階段）。
"none": 不驗證。完全不發送驗證信。
"""

#! Google 登入後自動建立帳號，不跳轉額外確認頁
SOCIALACCOUNT_AUTO_SIGNUP = True


#! 登入/登出後的跳轉頁面
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {"client_id": env("GOOGLE_CLIENT_ID"), "secret": env("GOOGLE_CLIENT_SECRET"), "key": ""},
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # * 確保這行有指向根目錄的 templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

#! 資料庫設定，django-environ 會自動解析 DATABASE_URL 並轉換為 Django 格式
DATABASES = {
    "default": env.db(),
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

#! 語系與時區設定
LANGUAGE_CODE = "zh-hant"
TIME_ZONE = "Asia/Taipei"
USE_I18N = True  # * 是否啟用 Django 的翻譯功能
USE_TZ = True  # * 時區感知，要在網頁上顯示時間時以 TIME_ZONE 設定為準

STATIC_URL = "static/"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"  # * 允許使用 Bootstrap 5
CRISPY_TEMPLATE_PACK = "bootstrap5"  # * 預設使用 Bootstrap 5 渲染
