# Generated by Django 6.0.3 on 2026-03-27 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_coins', models.IntegerField(default=0, verbose_name='總遊戲幣')),
                ('survivor_max_time', models.IntegerField(default=0, verbose_name='倖存者-最高存活秒數')),
                ('survivor_max_kills', models.IntegerField(default=0, verbose_name='倖存者-最高擊殺數')),
                ('survivor_hp_lv', models.IntegerField(default=0, verbose_name='倖存者-血量等級')),
                ('survivor_atk_lv', models.IntegerField(default=0, verbose_name='倖存者-攻擊等級')),
                ('survivor_speed_lv', models.IntegerField(default=0, verbose_name='倖存者-移速等級')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL, verbose_name='玩家')),
            ],
            options={
                'verbose_name': '玩家遊戲存檔',
                'verbose_name_plural': '玩家遊戲存檔',
            },
        ),
    ]
