# Generated by Django 6.0.3 on 2026-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurvivorLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='關卡名稱')),
                ('time_limit', models.IntegerField(default=300, verbose_name='通關時間(秒)')),
                ('spawn_rate_mult', models.FloatField(default=1.0, verbose_name='出怪頻率倍率(越高越快)')),
                ('stat_mult', models.FloatField(default=1.0, verbose_name='怪物屬性倍率(難度)')),
                ('win_bonus', models.IntegerField(default=100, verbose_name='通關獎勵金幣')),
            ],
            options={
                'verbose_name': '倖存者-關卡設定',
                'verbose_name_plural': '倖存者-關卡設定',
            },
        ),
        migrations.CreateModel(
            name='SurvivorMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='怪物名稱')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/monsters/', verbose_name='怪物圖片')),
                ('base_hp', models.IntegerField(default=10, verbose_name='基礎血量')),
                ('base_atk', models.IntegerField(default=5, verbose_name='基礎攻擊力')),
                ('base_speed', models.FloatField(default=1.5, verbose_name='基礎跑速')),
                ('base_size', models.IntegerField(default=15, verbose_name='碰撞體積(半徑)')),
            ],
            options={
                'verbose_name': '倖存者-怪物圖鑑',
                'verbose_name_plural': '倖存者-怪物圖鑑',
            },
        ),
    ]
