# Generated by Django 6.0.4 on 2026-04-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_survivorlevel_survivormonster'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualLifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='事件名稱')),
                ('event_type', models.CharField(choices=[('money_up', '獲得金錢'), ('money_down', '失去金錢'), ('stat_up', '提升屬性'), ('event_card', '抽事件卡')], max_length=20, verbose_name='事件類型')),
                ('effect_value', models.IntegerField(default=0, verbose_name='影響數值')),
                ('description', models.TextField(blank=True, verbose_name='事件描述')),
            ],
            options={
                'verbose_name': '虛擬人生-事件設定',
                'verbose_name_plural': '虛擬人生-事件設定',
            },
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='vl_cleared_boards',
            field=models.IntegerField(default=0, verbose_name='虛擬人生-通關地圖數'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='vl_dice_control_lv',
            field=models.IntegerField(default=0, verbose_name='虛擬人生-控骰能力等級'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='vl_max_money',
            field=models.IntegerField(default=0, verbose_name='虛擬人生-最高持有金錢'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='vl_start_money_lv',
            field=models.IntegerField(default=0, verbose_name='虛擬人生-初始資金等級'),
        ),
    ]
