# Generated by Django 6.0.4 on 2026-04-16 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_virtuallifeevent_gameprofile_vl_cleared_boards_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicTowerMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_id', models.IntegerField(unique=True, verbose_name='對應地圖代碼')),
                ('name', models.CharField(max_length=50, verbose_name='怪物名稱')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/mt_monsters/', verbose_name='上傳圖片')),
                ('hp', models.IntegerField(default=50, verbose_name='生命值')),
                ('atk', models.IntegerField(default=20, verbose_name='攻擊力')),
                ('def_stat', models.IntegerField(default=10, verbose_name='防禦力')),
                ('exp', models.IntegerField(default=5, verbose_name='掉落經驗')),
                ('gold', models.IntegerField(default=2, verbose_name='掉落金幣')),
            ],
            options={
                'verbose_name': '魔塔-怪物圖鑑',
                'verbose_name_plural': '魔塔-怪物圖鑑',
            },
        ),
        migrations.CreateModel(
            name='MagicTowerTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_id', models.IntegerField(unique=True, verbose_name='物件代碼')),
                ('name', models.CharField(max_length=50, verbose_name='物件名稱')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/mt_tiles/', verbose_name='上傳圖片')),
            ],
            options={
                'verbose_name': '魔塔-地圖物件圖鑑',
                'verbose_name_plural': '魔塔-地圖物件圖鑑',
            },
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='mt_atk_lv',
            field=models.IntegerField(default=0, verbose_name='魔塔-攻擊等級'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='mt_def_lv',
            field=models.IntegerField(default=0, verbose_name='魔塔-防禦等級'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='mt_hp_lv',
            field=models.IntegerField(default=0, verbose_name='魔塔-血量等級'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='mt_max_floor',
            field=models.IntegerField(default=0, verbose_name='魔塔-最高到達樓層'),
        ),
        migrations.CreateModel(
            name='MagicTowerSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=20, verbose_name='職業')),
                ('level', models.IntegerField(default=1, verbose_name='等級')),
                ('hp', models.IntegerField(default=1000, verbose_name='當前生命')),
                ('atk', models.IntegerField(default=10, verbose_name='攻擊力')),
                ('def_stat', models.IntegerField(default=10, verbose_name='防禦力')),
                ('exp', models.IntegerField(default=0, verbose_name='經驗值')),
                ('yellow_keys', models.IntegerField(default=0, verbose_name='黃鑰匙')),
                ('blue_keys', models.IntegerField(default=0, verbose_name='藍鑰匙')),
                ('current_floor', models.IntegerField(default=1, verbose_name='當前樓層')),
                ('map_states', models.JSONField(default=dict, verbose_name='各地圖狀態紀錄')),
                ('cleared_floors', models.JSONField(default=list, verbose_name='已通關樓層')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mt_save', to=settings.AUTH_USER_MODEL, verbose_name='玩家')),
            ],
            options={
                'verbose_name': '魔塔-玩家存檔',
                'verbose_name_plural': '魔塔-玩家存檔',
            },
        ),
    ]
