# Generated by Django 6.0.5 on 2026-07-03 05:38

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='LINE 群組識別碼')),
                ('title', encrypted_model_fields.fields.EncryptedCharField(verbose_name='行程標題')),
                ('location', encrypted_model_fields.fields.EncryptedCharField(verbose_name='活動地點')),
                ('notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='備註說明')),
                ('activity_type', models.CharField(choices=[('EAT', '吃飯聚餐'), ('EXHIBIT', '逛街展覽'), ('SPORT', '運動健身'), ('TRAVEL', '旅遊踏青'), ('OTHER', '其他活動')], default='OTHER', max_length=10, verbose_name='活動類型')),
                ('date_time', models.DateTimeField(verbose_name='行程時間')),
                ('notify_days_before', models.IntegerField(default=1, verbose_name='提前通知天數')),
                ('is_notified', models.BooleanField(default=False, verbose_name='是否已發送通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_itineraries', to=settings.AUTH_USER_MODEL, verbose_name='發起人')),
            ],
            options={
                'verbose_name': '行程管理',
                'verbose_name_plural': '行程管理',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='LineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=50, unique=True, verbose_name='LINE 用戶識別碼')),
                ('line_display_name', models.CharField(blank=True, max_length=100, verbose_name='LINE 顯示名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'LINE 個人檔案',
                'verbose_name_plural': 'LINE 個人檔案',
            },
        ),
    ]
