# Generated by Django 6.0.5 on 2026-07-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='notify_days_before',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='notify_minutes_before',
            field=models.IntegerField(default=1440, verbose_name='提前通知時間(分鐘)'),
        ),
    ]
