# Generated by Django 6.0.5 on 2026-07-03 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0002_remove_itinerary_notify_days_before_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=50, verbose_name='LINE 群組 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '群組成員關係',
                'verbose_name_plural': '群組成員關係',
                'unique_together': {('user', 'group_id')},
            },
        ),
    ]
