# Generated by Django 6.0.5 on 2026-07-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0003_groupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='activity_type',
            field=models.CharField(choices=[('EAT', '吃飯聚餐'), ('EXHIBIT', '逛街展覽'), ('SPORT', '運動健身'), ('TRAVEL', '旅遊踏青'), ('MOVIE', '看電影'), ('OTHER', '其他活動')], default='OTHER', max_length=10, verbose_name='活動類型'),
        ),
    ]
