# Generated by Django 6.0.7 on 2026-07-14 00:25

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0004_alter_itinerary_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='interested_users',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='[]', verbose_name='有興趣成員'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='related_links',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='[]', verbose_name='相關活動連結'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='行程時間'),
        ),
    ]
