# Generated by Django 6.0.7 on 2026-07-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0005_itinerary_interested_users_itinerary_related_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='是否已隱藏'),
        ),
    ]
