# Generated by Django 6.0.7 on 2026-07-14 03:31

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0006_itinerary_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', encrypted_model_fields.fields.EncryptedCharField(verbose_name='劇名')),
                ('category', models.CharField(default='其他', max_length=50, verbose_name='分類')),
                ('total_seasons', models.IntegerField(default=1, verbose_name='總季數')),
                ('total_episodes', models.IntegerField(default=0, verbose_name='總集數')),
                ('info_links', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='[]', verbose_name='相關資訊連結')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dramas', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '追劇主檔',
                'verbose_name_plural': '追劇主檔',
            },
        ),
        migrations.CreateModel(
            name='DramaRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='推薦心得語錄')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='是否已接受')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_manager.drama', verbose_name='追劇項目')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='推薦人')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='被推薦人')),
            ],
            options={
                'verbose_name': '追劇推薦記錄',
                'verbose_name_plural': '追劇推薦記錄',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL, verbose_name='好友')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '追劇好友關係',
                'verbose_name_plural': '追劇好友關係',
                'unique_together': {('user', 'friend')},
            },
        ),
        migrations.CreateModel(
            name='UserDramaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_season', models.IntegerField(default=1, verbose_name='目前看至第幾季')),
                ('current_episode', models.IntegerField(default=1, verbose_name='目前看至第幾集')),
                ('is_tracked', models.BooleanField(default=False, verbose_name='是否追蹤連結更新')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='line_manager.drama', verbose_name='追劇')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drama_progresses', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '個人追劇進度',
                'verbose_name_plural': '個人追劇進度',
                'unique_together': {('user', 'drama')},
            },
        ),
    ]
