# Generated by Django 6.1 on 2026-08-12 00:54

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0007_drama_dramarecommendation_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='image_url',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='預覽圖連結'),
        ),
    ]
