# Generated by Django 6.1 on 2026-08-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0009_dramarecommendation_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='dramarecommendation',
            name='status',
            field=models.CharField(choices=[('pending', '未讀/待處理'), ('accepted', '已加入清單'), ('rejected', '已拒絕'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='推薦狀態'),
        ),
    ]
