# Generated by Django 6.1 on 2026-08-24 03:11

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0010_dramarecommendation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeFranchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='作品系列名稱')),
                ('description', models.TextField(blank=True, verbose_name='系列簡介/說明')),
                ('cover_image_url', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='系列封面圖')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '動漫作品系列',
                'verbose_name_plural': '動漫作品系列',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='drama',
            name='media_type',
            field=models.CharField(choices=[('TV', 'TV 正篇 / 季番'), ('MOVIE', '劇場版 / 電影'), ('OVA', 'OVA / 特別篇'), ('RECAP', '總集篇')], default='TV', max_length=20, verbose_name='媒體類型'),
        ),
        migrations.AddField(
            model_name='drama',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dramas', to='line_manager.animefranchise', verbose_name='所屬作品系列'),
        ),
    ]
