# Generated by Django 6.1 on 2026-08-25 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0011_animefranchise_drama_media_type_drama_franchise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userdramaprogress',
            index=models.Index(fields=['drama'], name='line_manage_drama_i_184228_idx'),
        ),
        migrations.AddIndex(
            model_name='userdramaprogress',
            index=models.Index(fields=['user'], name='line_manage_user_id_9ab860_idx'),
        ),
    ]
