# Generated by Django 6.1 on 2026-08-27 01:52

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_manager', '0012_userdramaprogress_line_manage_drama_i_184228_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='mp3_links',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='[]', verbose_name='MP3 音樂播放清單'),
        ),
        migrations.AddField(
            model_name='drama',
            name='mp4_links',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='[]', verbose_name='MP4 影片播放清單'),
        ),
    ]
