# Generated by Django 6.0.5 on 2026-05-18 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='物品名稱')),
                ('description', models.TextField(blank=True, verbose_name='物品描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('accepted', '已接受'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發起時間')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer_system.item', verbose_name='轉移物品')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to=settings.AUTH_USER_MODEL, verbose_name='轉出者')),
            ],
            options={
                'verbose_name': '轉移紀錄',
                'verbose_name_plural': '轉移紀錄',
            },
        ),
    ]
