# Generated by Django 6.0.5 on 2026-05-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('accepted', '已接受'), ('rejected', '已拒絕'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態'),
        ),
    ]
