# Generated by Django 6.0.5 on 2026-05-25 03:06

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_system', '0002_alter_transferrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='status',
            field=django_fsm.FSMField(default='pending', max_length=50, protected=True, verbose_name='狀態'),
        ),
    ]
