# Generated by Django 6.0.4 on 2026-04-28 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, verbose_name='模型版本名稱')),
                ('model_file', models.FileField(upload_to='models/shih_hsiang/', verbose_name='模型檔案 (.pth)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
            ],
            options={
                'verbose_name': 'AI 模型',
                'verbose_name_plural': 'AI 模型管理',
            },
        ),
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/original/', verbose_name='原始圖片')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='images/result/', verbose_name='辨識結果圖片')),
                ('result_text', models.TextField(blank=True, null=True, verbose_name='辨識文字結果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('used_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sh_recognition.aimodel', verbose_name='使用模型')),
            ],
            options={
                'verbose_name': '圖片辨識紀錄',
                'verbose_name_plural': '圖片辨識紀錄管理',
            },
        ),
    ]
