# Generated by Django 6.0.4 on 2026-04-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='conf_threshold',
            field=models.FloatField(default=0.5, verbose_name='使用信心閥值'),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='has_object',
            field=models.BooleanField(default=False, verbose_name='是否有辨識到物體'),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='user_note',
            field=models.TextField(blank=True, null=True, verbose_name='使用者註記'),
        ),
    ]
